default: &default
  adapter:  postgresql
  encoding: utf-8
  username: <%= ENV.fetch("DB_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DB_PASSWORD", "postgres") %>
  pool:     8

development: &development
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "database") %>_development
  host:     <%= ENV.fetch("DB_PORT_5432_TCP_ADDR", "localhost") %>
  port:     <%= ENV.fetch("DB_PORT_5432_TCP_PORT", "5432") %>

production:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "database") %>_production
  host:     <%= ENV.fetch("DB_HOST", "localhost") %>
  port:     <%= ENV.fetch("DB_PORT", "5432") %>

test:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "database") %>_test
