default: &default
  adapter:  postgresql
  encoding: utf-8
  pool:     8
  password: <%= ENV.fetch("DB_PASSWORD", "postgres") %>
  username: <%= ENV.fetch("DB_USERNAME", "postgres") %>

development: &development
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "database") %>_development
  host:     <%= ENV.fetch("DB_PORT_5432_TCP_ADDR", "localhost") %>
  port:     <%= ENV.fetch("DB_PORT_5432_TCP_PORT", "5432") %>

production:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "database") %>_production
  host:     <%= ENV["DB_HOST"] %>
  port:     <%= ENV["DB_PORT"] %>

test:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "database") %>_test
  host:     <%= ENV.fetch("DB_PORT_5432_TCP_ADDR", "localhost") %>
  port:     <%= ENV.fetch("DB_PORT_5432_TCP_PORT", "5432") %>
