default: &default
  adapter:  postgresql
  encoding: utf-8
  username: postgres
  password: postgres
  host:     <%= ENV.fetch("DB_PORT_5432_TCP_ADDR", "localhost") %>
  port:     <%= ENV.fetch("DB_PORT_5432_TCP_PORT", "5432") %>
  pool:     8

development: &development
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "database") %>_development

production:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "database") %>_production

test:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "database") %>_test
